package template

import "github.com/gin-gonic/gin"

func RouteWebPages(route gin.IRouter) {
 route.GET("/", assetHandler(Indexhtml, "text/html; charset=utf-8", "no-cache"))
 route.HEAD("/", assetHandler(Indexhtml, "text/html; charset=utf-8", "no-cache"))
 route.GET("/THIRD_PARTY_NOTICES.txt", assetHandler(THIRDPARTYNOTICEStxt, "text/plain; charset=utf-8", "public, max-age=3600"))
 route.HEAD("/THIRD_PARTY_NOTICES.txt", assetHandler(THIRDPARTYNOTICEStxt, "text/plain; charset=utf-8", "public, max-age=3600"))
 route.GET("/assets/Add-CGwwx38m.js", assetHandler(AssetsAddCGwwx38mjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Add-CGwwx38m.js", assetHandler(AssetsAddCGwwx38mjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/AddTorrentModal-kisqd4g0.js", assetHandler(AssetsAddTorrentModalkisqd4g0js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/AddTorrentModal-kisqd4g0.js", assetHandler(AssetsAddTorrentModalkisqd4g0js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/Button-KTs46vB5.js", assetHandler(AssetsButtonKTs46vB5js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Button-KTs46vB5.js", assetHandler(AssetsButtonKTs46vB5js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/CacheMap-DAWPR6ly.js", assetHandler(AssetsCacheMapDAWPR6lyjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/CacheMap-DAWPR6ly.js", assetHandler(AssetsCacheMapDAWPR6lyjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/Dashboard-Bzm_B-y-.js", assetHandler(AssetsDashboardBzmByjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Dashboard-Bzm_B-y-.js", assetHandler(AssetsDashboardBzmByjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/FlowDiagnosticsDrawer-DRttquaT.js", assetHandler(AssetsFlowDiagnosticsDrawerDRttquaTjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/FlowDiagnosticsDrawer-DRttquaT.js", assetHandler(AssetsFlowDiagnosticsDrawerDRttquaTjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/GstRuntimeStatus-CHCq1YtW.js", assetHandler(AssetsGstRuntimeStatusCHCq1YtWjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/GstRuntimeStatus-CHCq1YtW.js", assetHandler(AssetsGstRuntimeStatusCHCq1YtWjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/PhonePairingModal-T6u_eQHe.js", assetHandler(AssetsPhonePairingModalT6ueQHejs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/PhonePairingModal-T6u_eQHe.js", assetHandler(AssetsPhonePairingModalT6ueQHejs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/PlaybackLinks-Ccfy1QQ_.js", assetHandler(AssetsPlaybackLinksCcfy1QQjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/PlaybackLinks-Ccfy1QQ_.js", assetHandler(AssetsPlaybackLinksCcfy1QQjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/PosterSearch-DyWxdSkx.js", assetHandler(AssetsPosterSearchDyWxdSkxjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/PosterSearch-DyWxdSkx.js", assetHandler(AssetsPosterSearchDyWxdSkxjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/Settings-4mIOB2sL.js", assetHandler(AssetsSettings4mIOB2sLjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Settings-4mIOB2sL.js", assetHandler(AssetsSettings4mIOB2sLjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/TorrentFilesDialog-P6MIKOzO.js", assetHandler(AssetsTorrentFilesDialogP6MIKOzOjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/TorrentFilesDialog-P6MIKOzO.js", assetHandler(AssetsTorrentFilesDialogP6MIKOzOjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/Torrents-rjhv5vDK.js", assetHandler(AssetsTorrentsrjhv5vDKjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Torrents-rjhv5vDK.js", assetHandler(AssetsTorrentsrjhv5vDKjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/VideoPlayer-CgF17rAG.js", assetHandler(AssetsVideoPlayerCgF17rAGjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/VideoPlayer-CgF17rAG.js", assetHandler(AssetsVideoPlayerCgF17rAGjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/client-Dr26AKOf.js", assetHandler(AssetsclientDr26AKOfjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/client-Dr26AKOf.js", assetHandler(AssetsclientDr26AKOfjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/clipboard-BX4bd3OW.js", assetHandler(AssetsclipboardBX4bd3OWjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/clipboard-BX4bd3OW.js", assetHandler(AssetsclipboardBX4bd3OWjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/createLucideIcon-D7zlQbrg.js", assetHandler(AssetscreateLucideIconD7zlQbrgjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/createLucideIcon-D7zlQbrg.js", assetHandler(AssetscreateLucideIconD7zlQbrgjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/format-B_YcZLV7.js", assetHandler(AssetsformatBYcZLV7js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/format-B_YcZLV7.js", assetHandler(AssetsformatBYcZLV7js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/hls-D9b4QHpD.js", assetHandler(AssetshlsD9b4QHpDjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/hls-D9b4QHpD.js", assetHandler(AssetshlsD9b4QHpDjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/index-CWFbkTKx.js", assetHandler(AssetsindexCWFbkTKxjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/index-CWFbkTKx.js", assetHandler(AssetsindexCWFbkTKxjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/index-DVKn9Oxb.css", assetHandler(AssetsindexDVKn9Oxbcss, "text/css; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/index-DVKn9Oxb.css", assetHandler(AssetsindexDVKn9Oxbcss, "text/css; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/integrations-WHdJYyGB.js", assetHandler(AssetsintegrationsWHdJYyGBjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/integrations-WHdJYyGB.js", assetHandler(AssetsintegrationsWHdJYyGBjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/preload-helper-uBIymjUX.js", assetHandler(AssetspreloadhelperuBIymjUXjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/preload-helper-uBIymjUX.js", assetHandler(AssetspreloadhelperuBIymjUXjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/redact-C8NqrjZt.js", assetHandler(AssetsredactC8NqrjZtjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/redact-C8NqrjZt.js", assetHandler(AssetsredactC8NqrjZtjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/rolldown-runtime-CbXtAM7H.js", assetHandler(AssetsrolldownruntimeCbXtAM7Hjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/rolldown-runtime-CbXtAM7H.js", assetHandler(AssetsrolldownruntimeCbXtAM7Hjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-CH9OFZ_8.js", assetHandler(AssetstranslationCH9OFZ8js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-CH9OFZ_8.js", assetHandler(AssetstranslationCH9OFZ8js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-CbreNevD.js", assetHandler(AssetstranslationCbreNevDjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-CbreNevD.js", assetHandler(AssetstranslationCbreNevDjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-ChhmwNkM.js", assetHandler(AssetstranslationChhmwNkMjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-ChhmwNkM.js", assetHandler(AssetstranslationChhmwNkMjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-CyLDA-mD.js", assetHandler(AssetstranslationCyLDAmDjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-CyLDA-mD.js", assetHandler(AssetstranslationCyLDAmDjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-DLyhR6O_.js", assetHandler(AssetstranslationDLyhR6Ojs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-DLyhR6O_.js", assetHandler(AssetstranslationDLyhR6Ojs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-DrVIB1xB.js", assetHandler(AssetstranslationDrVIB1xBjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-DrVIB1xB.js", assetHandler(AssetstranslationDrVIB1xBjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/useQuery-xJfTCyZ4.js", assetHandler(AssetsuseQueryxJfTCyZ4js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/useQuery-xJfTCyZ4.js", assetHandler(AssetsuseQueryxJfTCyZ4js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/browserconfig.xml", assetHandler(Browserconfigxml, "text/xml; charset=utf-8", "public, max-age=3600"))
 route.HEAD("/browserconfig.xml", assetHandler(Browserconfigxml, "text/xml; charset=utf-8", "public, max-age=3600"))
 route.GET("/dlnaicon-120.png", assetHandler(Dlnaicon120png, "image/png", "public, max-age=3600"))
 route.HEAD("/dlnaicon-120.png", assetHandler(Dlnaicon120png, "image/png", "public, max-age=3600"))
 route.GET("/dlnaicon-48.png", assetHandler(Dlnaicon48png, "image/png", "public, max-age=3600"))
 route.HEAD("/dlnaicon-48.png", assetHandler(Dlnaicon48png, "image/png", "public, max-age=3600"))
 route.GET("/favicon-16x16.png", assetHandler(Favicon16x16png, "image/png", "public, max-age=3600"))
 route.HEAD("/favicon-16x16.png", assetHandler(Favicon16x16png, "image/png", "public, max-age=3600"))
 route.GET("/favicon-32x32.png", assetHandler(Favicon32x32png, "image/png", "public, max-age=3600"))
 route.HEAD("/favicon-32x32.png", assetHandler(Favicon32x32png, "image/png", "public, max-age=3600"))
 route.GET("/favicon.ico", assetHandler(Faviconico, "image/vnd.microsoft.icon", "public, max-age=3600"))
 route.HEAD("/favicon.ico", assetHandler(Faviconico, "image/vnd.microsoft.icon", "public, max-age=3600"))
 route.GET("/icon.png", assetHandler(Iconpng, "image/png", "public, max-age=3600"))
 route.HEAD("/icon.png", assetHandler(Iconpng, "image/png", "public, max-age=3600"))
 route.GET("/index.html", assetHandler(Indexhtml, "text/html; charset=utf-8", "no-cache"))
 route.HEAD("/index.html", assetHandler(Indexhtml, "text/html; charset=utf-8", "no-cache"))
 route.GET("/logo.png", assetHandler(Logopng, "image/png", "public, max-age=3600"))
 route.HEAD("/logo.png", assetHandler(Logopng, "image/png", "public, max-age=3600"))
 route.GET("/mstile-150x150.png", assetHandler(Mstile150x150png, "image/png", "public, max-age=3600"))
 route.HEAD("/mstile-150x150.png", assetHandler(Mstile150x150png, "image/png", "public, max-age=3600"))
 route.GET("/site.webmanifest", assetHandler(Sitewebmanifest, "application/manifest+json", "no-cache"))
 route.HEAD("/site.webmanifest", assetHandler(Sitewebmanifest, "application/manifest+json", "no-cache"))
}
