package template

import "github.com/gin-gonic/gin"

func RouteWebPages(route gin.IRouter) {
 route.GET("/", assetHandler(Indexhtml, "text/html; charset=utf-8", "no-cache"))
 route.HEAD("/", assetHandler(Indexhtml, "text/html; charset=utf-8", "no-cache"))
 route.GET("/THIRD_PARTY_NOTICES.txt", assetHandler(THIRDPARTYNOTICEStxt, "text/plain; charset=utf-8", "public, max-age=3600"))
 route.HEAD("/THIRD_PARTY_NOTICES.txt", assetHandler(THIRDPARTYNOTICEStxt, "text/plain; charset=utf-8", "public, max-age=3600"))
 route.GET("/assets/Add-BY0RuTri.js", assetHandler(AssetsAddBY0RuTrijs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Add-BY0RuTri.js", assetHandler(AssetsAddBY0RuTrijs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/AddTorrentModal-DYWo7wo9.js", assetHandler(AssetsAddTorrentModalDYWo7wo9js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/AddTorrentModal-DYWo7wo9.js", assetHandler(AssetsAddTorrentModalDYWo7wo9js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/Button-KTs46vB5.js", assetHandler(AssetsButtonKTs46vB5js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Button-KTs46vB5.js", assetHandler(AssetsButtonKTs46vB5js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/CacheMap-BGGmal-V.js", assetHandler(AssetsCacheMapBGGmalVjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/CacheMap-BGGmal-V.js", assetHandler(AssetsCacheMapBGGmalVjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/Dashboard-Dmhmfnq0.js", assetHandler(AssetsDashboardDmhmfnq0js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Dashboard-Dmhmfnq0.js", assetHandler(AssetsDashboardDmhmfnq0js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/FlowDiagnosticsDrawer-CpH0uzNd.js", assetHandler(AssetsFlowDiagnosticsDrawerCpH0uzNdjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/FlowDiagnosticsDrawer-CpH0uzNd.js", assetHandler(AssetsFlowDiagnosticsDrawerCpH0uzNdjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/GstRuntimeStatus-VUjst_HI.js", assetHandler(AssetsGstRuntimeStatusVUjstHIjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/GstRuntimeStatus-VUjst_HI.js", assetHandler(AssetsGstRuntimeStatusVUjstHIjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/PhonePairingModal-CPqPdt8q.js", assetHandler(AssetsPhonePairingModalCPqPdt8qjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/PhonePairingModal-CPqPdt8q.js", assetHandler(AssetsPhonePairingModalCPqPdt8qjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/PlaybackLinks-Ccfy1QQ_.js", assetHandler(AssetsPlaybackLinksCcfy1QQjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/PlaybackLinks-Ccfy1QQ_.js", assetHandler(AssetsPlaybackLinksCcfy1QQjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/PosterSearch-DyWxdSkx.js", assetHandler(AssetsPosterSearchDyWxdSkxjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/PosterSearch-DyWxdSkx.js", assetHandler(AssetsPosterSearchDyWxdSkxjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/Settings-BKxun42h.js", assetHandler(AssetsSettingsBKxun42hjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Settings-BKxun42h.js", assetHandler(AssetsSettingsBKxun42hjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/TorrentFilesDialog-szRrA80d.js", assetHandler(AssetsTorrentFilesDialogszRrA80djs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/TorrentFilesDialog-szRrA80d.js", assetHandler(AssetsTorrentFilesDialogszRrA80djs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/Torrents-Bi9LsMaU.js", assetHandler(AssetsTorrentsBi9LsMaUjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/Torrents-Bi9LsMaU.js", assetHandler(AssetsTorrentsBi9LsMaUjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/VideoPlayer-Cf80MWiX.js", assetHandler(AssetsVideoPlayerCf80MWiXjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/VideoPlayer-Cf80MWiX.js", assetHandler(AssetsVideoPlayerCf80MWiXjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/client-Dr26AKOf.js", assetHandler(AssetsclientDr26AKOfjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/client-Dr26AKOf.js", assetHandler(AssetsclientDr26AKOfjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/clipboard-BX4bd3OW.js", assetHandler(AssetsclipboardBX4bd3OWjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/clipboard-BX4bd3OW.js", assetHandler(AssetsclipboardBX4bd3OWjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/createLucideIcon-D7zlQbrg.js", assetHandler(AssetscreateLucideIconD7zlQbrgjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/createLucideIcon-D7zlQbrg.js", assetHandler(AssetscreateLucideIconD7zlQbrgjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/format-B_YcZLV7.js", assetHandler(AssetsformatBYcZLV7js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/format-B_YcZLV7.js", assetHandler(AssetsformatBYcZLV7js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/hls-D9b4QHpD.js", assetHandler(AssetshlsD9b4QHpDjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/hls-D9b4QHpD.js", assetHandler(AssetshlsD9b4QHpDjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/index-BAH-nO5A.js", assetHandler(AssetsindexBAHnO5Ajs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/index-BAH-nO5A.js", assetHandler(AssetsindexBAHnO5Ajs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/index-DVKn9Oxb.css", assetHandler(AssetsindexDVKn9Oxbcss, "text/css; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/index-DVKn9Oxb.css", assetHandler(AssetsindexDVKn9Oxbcss, "text/css; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/integrations-WHdJYyGB.js", assetHandler(AssetsintegrationsWHdJYyGBjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/integrations-WHdJYyGB.js", assetHandler(AssetsintegrationsWHdJYyGBjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/preload-helper-uBIymjUX.js", assetHandler(AssetspreloadhelperuBIymjUXjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/preload-helper-uBIymjUX.js", assetHandler(AssetspreloadhelperuBIymjUXjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/redact-C8NqrjZt.js", assetHandler(AssetsredactC8NqrjZtjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/redact-C8NqrjZt.js", assetHandler(AssetsredactC8NqrjZtjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/rolldown-runtime-CbXtAM7H.js", assetHandler(AssetsrolldownruntimeCbXtAM7Hjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/rolldown-runtime-CbXtAM7H.js", assetHandler(AssetsrolldownruntimeCbXtAM7Hjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-BDIIZ4z3.js", assetHandler(AssetstranslationBDIIZ4z3js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-BDIIZ4z3.js", assetHandler(AssetstranslationBDIIZ4z3js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-BJTOjV1o.js", assetHandler(AssetstranslationBJTOjV1ojs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-BJTOjV1o.js", assetHandler(AssetstranslationBJTOjV1ojs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-BZ8kwz1c.js", assetHandler(AssetstranslationBZ8kwz1cjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-BZ8kwz1c.js", assetHandler(AssetstranslationBZ8kwz1cjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-CJ0GZYvA.js", assetHandler(AssetstranslationCJ0GZYvAjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-CJ0GZYvA.js", assetHandler(AssetstranslationCJ0GZYvAjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-DRZDcE4R.js", assetHandler(AssetstranslationDRZDcE4Rjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-DRZDcE4R.js", assetHandler(AssetstranslationDRZDcE4Rjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/translation-UeTjBAnL.js", assetHandler(AssetstranslationUeTjBAnLjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/translation-UeTjBAnL.js", assetHandler(AssetstranslationUeTjBAnLjs, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/assets/useQuery-xJfTCyZ4.js", assetHandler(AssetsuseQueryxJfTCyZ4js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.HEAD("/assets/useQuery-xJfTCyZ4.js", assetHandler(AssetsuseQueryxJfTCyZ4js, "text/javascript; charset=utf-8", "public, max-age=31536000, immutable"))
 route.GET("/browserconfig.xml", assetHandler(Browserconfigxml, "text/xml; charset=utf-8", "public, max-age=3600"))
 route.HEAD("/browserconfig.xml", assetHandler(Browserconfigxml, "text/xml; charset=utf-8", "public, max-age=3600"))
 route.GET("/dlnaicon-120.png", assetHandler(Dlnaicon120png, "image/png", "public, max-age=3600"))
 route.HEAD("/dlnaicon-120.png", assetHandler(Dlnaicon120png, "image/png", "public, max-age=3600"))
 route.GET("/dlnaicon-48.png", assetHandler(Dlnaicon48png, "image/png", "public, max-age=3600"))
 route.HEAD("/dlnaicon-48.png", assetHandler(Dlnaicon48png, "image/png", "public, max-age=3600"))
 route.GET("/favicon-16x16.png", assetHandler(Favicon16x16png, "image/png", "public, max-age=3600"))
 route.HEAD("/favicon-16x16.png", assetHandler(Favicon16x16png, "image/png", "public, max-age=3600"))
 route.GET("/favicon-32x32.png", assetHandler(Favicon32x32png, "image/png", "public, max-age=3600"))
 route.HEAD("/favicon-32x32.png", assetHandler(Favicon32x32png, "image/png", "public, max-age=3600"))
 route.GET("/favicon.ico", assetHandler(Faviconico, "image/vnd.microsoft.icon", "public, max-age=3600"))
 route.HEAD("/favicon.ico", assetHandler(Faviconico, "image/vnd.microsoft.icon", "public, max-age=3600"))
 route.GET("/icon.png", assetHandler(Iconpng, "image/png", "public, max-age=3600"))
 route.HEAD("/icon.png", assetHandler(Iconpng, "image/png", "public, max-age=3600"))
 route.GET("/index.html", assetHandler(Indexhtml, "text/html; charset=utf-8", "no-cache"))
 route.HEAD("/index.html", assetHandler(Indexhtml, "text/html; charset=utf-8", "no-cache"))
 route.GET("/logo.png", assetHandler(Logopng, "image/png", "public, max-age=3600"))
 route.HEAD("/logo.png", assetHandler(Logopng, "image/png", "public, max-age=3600"))
 route.GET("/mstile-150x150.png", assetHandler(Mstile150x150png, "image/png", "public, max-age=3600"))
 route.HEAD("/mstile-150x150.png", assetHandler(Mstile150x150png, "image/png", "public, max-age=3600"))
 route.GET("/site.webmanifest", assetHandler(Sitewebmanifest, "application/manifest+json", "no-cache"))
 route.HEAD("/site.webmanifest", assetHandler(Sitewebmanifest, "application/manifest+json", "no-cache"))
}
